const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const root={};vm.runInNewContext(fs.readFileSync('zeekr_control/static/trip-tags.js','utf8'),{window:root});
const simplify=root.TripTagsPage.freehandVertices;
assert.equal(typeof simplify,'function','Freehand ring simplifier exists');
const point=(x,y)=>({x,y,lat:x/1000,lng:y/1000});
const rectangle=[];
for(let x=0;x<=200;x++)rectangle.push(point(x,0));
for(let y=1;y<=120;y++)rectangle.push(point(200,y));
for(let x=199;x>=0;x--)rectangle.push(point(x,120));
for(let y=119;y>=0;y--)rectangle.push(point(0,y));
const ring=simplify(rectangle);
assert.equal(ring.length,4,'Dense mouse path keeps four corners without duplicate closure');
assert.deepEqual(JSON.parse(JSON.stringify(ring)),[[0,0],[.2,0],[.2,.12],[0,.12]]);
assert.equal(simplify([point(0,0),point(1,0)]).length,0,'Click/tiny stroke cannot create a polygon');
assert.equal(simplify([point(0,0),point(100,0),point(200,0)]).length,0,'A line is not a region');
const round=Array.from({length:1200},(_,i)=>point(200+150*Math.cos(i*Math.PI/600),200+150*Math.sin(i*Math.PI/600)));
const circle=simplify(round);assert.ok(circle.length>=8&&circle.length<=100);
assert.ok(circle.every(v=>v.every(Number.isFinite)));
console.log('FREEHAND_REGION_LOGIC_PASS');
