const assert=require('node:assert/strict');
const {fixture}=require('./ui_insight_helpers.cjs');
(async()=>{const f=await fixture(),{page}=f;try{
 await page.getByRole('button',{name:'用车账本',exact:true}).click();await page.getByRole('button',{name:'生活账本',exact:true}).click();await page.getByRole('button',{name:'查询生活账本',exact:true}).click();await page.locator('#life-total').waitFor();await page.getByRole('button',{name:'新增支出',exact:true}).click();
 await page.getByLabel('支出日期',{exact:true}).fill('2026-09-20');await page.getByLabel('支出名称',{exact:true}).fill('历史支出');await page.getByLabel('实际支出金额（元）',{exact:true}).fill('12');await page.getByRole('button',{name:'保存支出',exact:true}).click();await page.getByText(/已切换到支出所在月份/).waitFor();await page.locator('[data-life-expense]').filter({hasText:'历史支出'}).waitFor();
 await page.getByRole('button',{name:'总览',exact:true}).click();await page.getByRole('button',{name:'用车账本',exact:true}).click();assert.equal(await page.getByRole('button',{name:'生活账本',exact:true}).getAttribute('aria-pressed'),'true');
 await page.getByRole('button',{name:'用车日历',exact:true}).click();await page.getByLabel('日历月份',{exact:true}).fill('2026-09');await page.getByRole('button',{name:'读取用车日历',exact:true}).click();await page.locator('[data-calendar-day="2026-09-19"]').click();await page.getByRole('button',{name:'打开充电账本',exact:true}).click();await page.locator('#ledger-range').waitFor();assert.equal(await page.locator('#ledger-month').inputValue(),'2026-09');await page.getByRole('button',{name:'返回来源页面',exact:true}).click();await page.locator('[data-calendar-day="2026-09-19"]').waitFor();assert.equal(new URL(page.url()).searchParams.get('p'),'calendar');await page.evaluate(async()=>{const book=await fetch('/api/insights/ledger?date=2026-09-01').then(r=>r.json());const r=await fetch('/api/insights/ledger',{method:'POST',headers:{'Content-Type':'application/json','X-Request-Key':state.request_key},body:JSON.stringify({action:'save',revision:book.revision,context:book.context,event_id:'report-charge',date:'2026-10-02',source:'home',amount:'30',note:'跨月账单'})});if(!r.ok)throw Error('fixture bill save failed');});
 await page.locator('[data-calendar=ledger-event][data-id=report-charge]').click();await page.waitForFunction(()=>document.querySelector('#ledger-date')?.value==='2026-10-02');assert.equal(await page.locator('#ledger-month').inputValue(),'2026-10');assert.equal(await page.locator('#ledger-amount').inputValue(),'30.00');
 assert.deepEqual(f.errors,[]);console.log('BOOKS_NAVIGATION_PASS');
}finally{await f.close()}})().catch(e=>{console.error(e);process.exitCode=1});
