const assert=require('node:assert/strict');
const {fixture,layouts}=require('./ui_insight_helpers.cjs');
(async()=>{
 const f=await fixture(),{page,origin}=f;
 try{
  const state=await (await page.request.get(origin+'/api/state')).json();
  const saved=await page.request.post(origin+'/api/insights/ledger',{headers:{Origin:origin,'X-Request-Key':state.request_key},data:{action:'save',context:state.insights_context,revision:0,event_id:'report-charge',date:'2026-09-19',source:'home',metered_kwh:'12.3',unit_price:'.75',service_fee:'2',parking_fee:'3',note:'合成保留字段'}});
  assert.equal(saved.status(),200);
  await page.getByRole('button',{name:'用车日历',exact:true}).click();
  await page.getByLabel('日历月份',{exact:true}).fill('2026-09');
  await page.getByRole('button',{name:'读取用车日历',exact:true}).click();
  await page.locator('.calendar-summary').waitFor();
  assert.match(await page.locator('.calendar-summary').innerText(),/67.*3 \/ 3/s);
  assert.match(await page.locator('#calendar-pending-total').innerText(),/1/);
  await page.locator('#calendar-pending-total').click();
  assert.equal(await page.locator('#calendar-selected').inputValue(),'2026-09-19');
  assert.equal(await page.locator('#calendar-view').inputValue(),'pending');
  await page.reload();await page.locator('.calendar-summary').waitFor();
  assert.equal(await page.locator('#calendar-selected').inputValue(),'2026-09-19');
  assert.equal(await page.locator('#calendar-view').inputValue(),'pending');
  await page.locator('[data-calendar-bill="report-charge"]').click();
  await page.locator('#calendar-bill-amount').fill('0');
  await page.evaluate(()=>render());
  assert.equal(await page.locator('#calendar-bill-amount').inputValue(),'0');
  await page.route('**/api/insights/ledger',route=>route.request().method()==='POST'?route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'合成版本冲突'})}):route.continue());
  await page.getByRole('button',{name:'保存金额',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'合成版本冲突'}).waitFor();
  assert.equal(await page.locator('#calendar-bill-amount').inputValue(),'0');
  await page.unroute('**/api/insights/ledger');
  await page.getByRole('button',{name:'读取用车日历',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('[role=status]')?.textContent.includes('正在读取'));
  assert.equal(await page.locator('#calendar-bill-amount').inputValue(),'0');
  await page.locator('#calendar-bill-amount').press('Enter');
  await page.waitForFunction(()=>document.querySelector('#calendar-pending-total')?.innerText.includes('本月没有待补'));
  const book=await (await page.request.get(origin+'/api/insights/ledger?date=2026-09-01')).json();
  const bill=book.entries[0];
  assert.equal(bill.actual_cents,0);assert.equal(bill.metered_kwh,12.3);assert.equal(bill.unit_price,'0.75');
  assert.equal(bill.service_fee_cents,200);assert.equal(bill.parking_fee_cents,300);assert.equal(bill.note,'合成保留字段');assert.equal(bill.source,'home');
  await page.locator('#calendar-view').selectOption('cost');
  assert.match(await page.locator('[data-calendar-day="2026-09-19"]').innerText(),/0.00/);
  await page.locator('[data-calendar-day="2026-09-20"]').click();
  assert.match(await page.locator('#calendar-day-detail').innerText(),/20 km/);
  await page.goBack();await page.waitForFunction(()=>document.querySelector('#calendar-selected')?.value==='2026-09-19');
  await page.locator('.calendar-summary').waitFor();
  await page.locator('#calendar-view').selectOption('distance');
  await layouts(page,'calendar-review');
  assert.deepEqual(f.errors,[]);assert.deepEqual(f.external,[]);
  assert.ok(f.posts.every(url=>url===origin+'/api/insights/ledger'));
  console.log('CALENDAR_REVIEW_PASS: month/day metrics, pending, URL refresh/back, zero bill, preserved fields, responsive themes and no cloud');
 }finally{await f.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
