// Real local review API, synthetic vehicle fixture. Never accesses an owner session.
const {chromium} = require('playwright');
const {spawn} = require('node:child_process');
const assert = require('node:assert/strict');
const path = require('node:path');
(async () => {
  const server = spawn('python3', [path.join(__dirname, 'web_fixture.py')]);
  let browser;
  try {
    const port = await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(Error('Fixture did not start')), 10000);
      server.stdout.once('data', data => {clearTimeout(timer); resolve(Number(String(data).trim()));});
      server.once('error', reject);
    });
    browser = await chromium.launch({headless:true, ...(process.env.CHROMIUM_EXECUTABLE ? {executablePath:process.env.CHROMIUM_EXECUTABLE} : {})});
    const page = await browser.newPage({viewport:{width:1500,height:1050}});
    page.setDefaultTimeout(7000);
    const errors = [];
    page.on('pageerror', error => {errors.push(error.message);console.error(error.message);});
    await page.goto(`http://127.0.0.1:${port}`);
    await page.getByRole('button',{name:'刷新状态',exact:true}).click();
    await page.getByRole('button',{name:'用车研究',exact:true}).click();
    await page.getByRole('button',{name:'参数研究与核实',exact:true}).first().click();
    await page.locator('#search').fill('mainBatteryStatus.chargeLevel');
    await page.locator('[data-review-path]').click();
    assert.match(await page.locator('#review-panel h2').innerText(), /低压辅助电池/);
    assert.match(await page.getByLabel('词典参考',{exact:true}).innerText(), /术语推测不等于状态码已确认/);
    await page.getByRole('button',{name:'编辑核实',exact:true}).click();
    assert.equal(await page.getByLabel('确认含义',{exact:true}).inputValue(), '');
    const sourceLink = page.getByLabel('词典参考',{exact:true}).getByRole('link');
    assert.match(await sourceLink.getAttribute('href'), /^https:\/\/github.com\/RexzeLu\/zeekr_ha/);
    const rawBefore = await page.locator('.review-snapshot strong').innerText();
    assert.equal(rawBefore, '96');
    await page.locator('#search').fill('steerWhlHeatingSts');
    await page.locator('[data-review-path]').click();
    await page.getByLabel('确认含义',{exact:true}).fill('关闭');
    await page.getByLabel('实际观察',{exact:true}).fill('车机显示关闭');
    await page.getByLabel('核实场景',{exact:true}).fill('停车');
    await page.getByRole('button',{name:'保存并下一项',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('已保存'));
    assert.match(await page.locator('#field-results').innerText(), /已确认/);
    await page.reload();
    await page.getByRole('button',{name:'参数研究与核实',exact:true}).first().click();
    await page.locator('#search').fill('steerWhlHeatingSts');
    await page.locator('[data-review-path]').click();
    await page.getByRole('button',{name:'编辑核实',exact:true}).click();
    assert.equal(await page.getByLabel('确认含义',{exact:true}).inputValue(), '关闭');
    await page.getByLabel('备注',{exact:true}).fill('未保存草稿 <img src=x onerror=alert(1)>');
    await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
    const noteTopBefore = await page.locator('#review-note').evaluate(el=>el.getBoundingClientRect().top);
    // A new cached observation triggers the ordinary polling/render path.
    await page.route('**/api/state', async route => {
      const response = await route.fetch();
      const data = await response.json();
      data.read_time += 1000;
      const field = data.model.fields.find(f => f.key === 'steerWhlHeatingSts');
      field.raw = '3'; field.value = '3';
      await route.fulfill({response,json:data});
    });
    await page.evaluate(()=>pollState(true));
    await page.waitForFunction(() => document.querySelector('#review-live-notice')?.textContent.includes('变化'),{},{timeout:12000});
    assert.equal(await page.getByLabel('备注',{exact:true}).inputValue(), '未保存草稿 <img src=x onerror=alert(1)>');
    const noteAfter=await page.locator('#review-note').evaluate(el=>({top:el.getBoundingClientRect().top,scroll:scrollY,focus:document.activeElement.id}));
    assert.ok(Math.abs(noteAfter.top-noteTopBefore)<3,JSON.stringify({message:'Polling must preserve the form scroll position',before:noteTopBefore,after:noteAfter}));
    assert.match(await page.locator('#field-results').innerText(), /部分确认/);
    assert.match(await page.locator('#review-panel').innerText(), /2/);
    await page.getByRole('button',{name:'保存',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#review-save-status')?.textContent === '已保存');
    await page.getByRole('button',{name:'撤销上次操作',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('已撤销'));
    const reviews = await page.evaluate(async () => (await (await fetch('/api/state')).json()).field_reviews.records);
    assert.equal(reviews.length,1);
    assert.equal(reviews[0].raw,'2');
    assert.equal(reviews[0].note,'');
    await page.getByRole('button',{name:'清除本条确认',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('已清除'));
    assert.match(await page.locator('#field-results').innerText(), /待核实/);
    await page.getByRole('button',{name:'撤销上次操作',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('已撤销'));
    await page.unroute('**/api/state');
    await page.evaluate(async () => {await pollState(true);});
    await page.getByRole('button',{name:'本字段不适用',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#review-save-status')?.textContent === '已保存');
    assert.match(await page.locator('#field-results').innerText(), /不适用/);
    await page.getByRole('button',{name:'撤销上次操作',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('已撤销'));
    await page.unroute('**/api/state');
    await page.locator('#search').fill('interiorTemp');
    await page.locator('[data-review-path]').click();
    await page.getByLabel('核实范围',{exact:true}).selectOption('field');
    await page.getByLabel('确认含义',{exact:true}).fill('车内温度');
    await page.getByLabel('单位（可选）',{exact:true}).fill('°C');
    await page.getByRole('button',{name:'保存',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#review-save-status')?.textContent === '已保存');
    await page.route('**/api/state', async route => {
      const response = await route.fetch(); const data = await response.json(); data.read_time += 2000;
      const field = data.model.fields.find(f => f.key === 'interiorTemp'); field.raw='28';field.value='28°C';
      await route.fulfill({response,json:data});
    });
    await page.waitForFunction(() => document.querySelector('#review-live-notice')?.textContent.includes('变化'),{},{timeout:12000});
    assert.match(await page.locator('#field-results').innerText(), /已确认/);
    await page.locator('#search').fill('');
    await page.getByRole('button',{name:'暂时跳过',exact:true}).click();
    const firstPath = await page.locator('#review-panel .review-path').innerText();
    await page.getByLabel('确认含义',{exact:true}).fill('测试含义');
    await page.getByRole('button',{name:'保存并下一项',exact:true}).click();
    await page.waitForFunction(previous => document.querySelector('#review-panel .review-path')?.textContent !== previous,firstPath);
    const secondPath = await page.locator('#review-panel .review-path').innerText();
    assert.notEqual(secondPath,firstPath);
    // Errors retain form data and leave progress unchanged.
    await page.route('**/api/field-reviews', route => route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'模拟存储失败'})}));
    await page.getByLabel('确认含义',{exact:true}).fill('保留填写内容');
    await page.getByRole('button',{name:'保存',exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#review-error')?.textContent.includes('模拟存储失败'));
    assert.equal(await page.getByLabel('确认含义',{exact:true}).inputValue(),'保留填写内容');
    await page.unroute('**/api/field-reviews');
    await page.getByRole('button',{name:'放弃草稿',exact:true}).click();
    await page.evaluate(() => {window.scrollTo(0,0);document.querySelector('#toast').hidden=true;});
    await page.screenshot({path:'/tmp/zeekr-field-reviews.png',fullPage:true});
    assert.deepEqual(errors,[]);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false);
    console.log('Parameter review UI passed: persistence, enum/numeric scope, not applicable, draft and scroll preservation, next item, errors, clear and undo.');
  } finally {if(browser) await browser.close(); server.kill('SIGTERM');}
})().catch(error => {console.error(error);process.exitCode=1;});
