// Desktop-only synthetic integration; production archive is never included here.
const {fixture}=require('./ui_insight_helpers.cjs'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const f=await fixture(),{page}=f;try{
const context=await page.evaluate(()=>state.insights_context);let reads=0,release,posts=[];
const path='additionalVehicleStatus.drivingSafetyStatus.electricParkBrakeStatus';
const candidate={path,name:'电子驻车',group:'门窗与安全',kind:'enum',pending:true,evidence:'待解释',status:'varied',distinct:2,count:12,
inside:{'"1"':5},outside:{'"0"':6,'"1"':1},unknown:{},displayed_values:['"1"','"0"'],other_values:0,
transitions:{both:2,state_only:1,field_only:3,gaps:1,unavailable:1},examples:{both:[{before:1789884000000,after:1789884060000,before_value:'"0"',after_value:'"1"',before_state:false,after_state:true}],state_only:[],field_only:[]},proposal:{source:'自动假设，未确认',meaning:'大胆假设：0=驻车制动释放，1=驻车制动生效。',basis:'两种反例共同保留。',next:'回看反例，必要时推翻假设。'}};
let data={context,start_date:'2026-09-20',end_date:'2026-09-20',state:'parked',anchor:'',value:'',catalog:217,reads:15,valid_samples:12,excluded:1,collapsed:2,boundary_unknown:0,source:'合成归档',target_true:5,target_false:7,target_unknown:0,candidates:[candidate],reviews:{vehicle:'synthetic-car',revision:0,records:[]}};
await page.route('**/api/insights/hypotheses?*',async route=>{reads++;if(reads===2)await new Promise(r=>release=r);await route.fulfill({json:data})});
await page.route('**/api/field-reviews',async route=>{const body=route.request().postDataJSON();posts.push(body);await route.fulfill({json:{vehicle:'synthetic-car',revision:1,records:[{path,scope:'field',status:'question',meaning:body.meaning,note:body.note}]}})});
await page.getByRole('button',{name:'假设与验证',exact:true}).click();assert.equal(reads,0);
await page.locator('#hypothesis-start').fill('2026-09-20');await page.locator('#hypothesis-end').fill('2026-09-20');assert.equal(reads,0);
await page.getByRole('button',{name:'起草假设并寻找证据',exact:true}).click();await page.locator('#hypothesis-meaning').waitFor();
assert.match(await page.locator('.hypothesis-evidence').innerText(),/状态变，参数没变/);assert.match(await page.locator('.hypothesis-evidence').innerText(),/参数变，状态没变/);assert.match(await page.locator('#hypothesis-meaning').inputValue(),/驻车制动/);
await page.locator('#hypothesis-reason').fill('留住反例，不直接确认。');await page.getByRole('button',{name:'保存为待核实假设',exact:true}).click();await page.getByText('待核实假设已保存，运行解码未改变。',{exact:true}).waitFor();assert.equal(posts.length,1);assert.equal(posts[0].status,'question');assert.equal(posts[0].hypothesis_context,context);assert.equal(posts[0].observation,'留住反例，不直接确认。');
for(const theme of ['light','dark']){await page.getByLabel('外观',{exact:true}).selectOption(theme);for(const width of [1440,1280,1024]){await page.setViewportSize({width,height:1050});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,JSON.stringify({width,theme,overflow:await page.evaluate(()=>[...document.querySelectorAll('.hypothesis-workspace *')].filter(e=>e.getBoundingClientRect().right>innerWidth).slice(0,6).map(e=>({tag:e.tagName,cls:e.className,right:e.getBoundingClientRect().right})))}));if(width===1440){fs.mkdirSync('/tmp/zeekr-hypothesis-qa',{recursive:true});await page.screenshot({path:`/tmp/zeekr-hypothesis-qa/${theme}.png`,fullPage:true})}}}
await page.locator('#hypothesis-condition').selectOption('anchor');assert.equal(await page.getByRole('button',{name:'起草假设并寻找证据',exact:true}).isDisabled(),true);await page.locator('#hypothesis-anchor').selectOption(path);await page.locator('#hypothesis-value').fill('"1"');assert.equal(await page.getByRole('button',{name:'起草假设并寻找证据',exact:true}).isDisabled(),false);
await page.getByRole('button',{name:'起草假设并寻找证据',exact:true}).click();await page.getByRole('button',{name:'正在寻找…',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'正在寻找…',exact:true}).isDisabled(),true);
await page.evaluate(()=>{state.insights_context='synthetic-new-owner';render()});while(!release)await new Promise(r=>setTimeout(r,10));release();await page.waitForTimeout(150);assert.equal(await page.locator('#hypothesis-meaning').count(),0);
assert.deepEqual(f.errors,[]);console.log('DESKTOP_HYPOTHESIS_PASS manual query, bold draft, both counterexamples, guarded question save, context cancellation, 6 layouts');
}finally{await f.close()}})().catch(e=>{console.error(e);process.exitCode=1});
