const assert=require('node:assert/strict');
const {fixture}=require('./ui_insight_helpers.cjs');
(async()=>{const f=await fixture({initialResearch:false}),{page}=f;try{
  await page.locator('#overview-cost-value').waitFor();
  assert.equal(await page.evaluate(()=>typeof window.VehicleResearchPage),'undefined','research module not loaded on overview');
  assert.equal(await page.evaluate(()=>typeof window.ChargeLedgerPage),'undefined','ledger module not loaded on overview');
  let requests=0,release;const gate=new Promise(resolve=>release=resolve);
  await page.route('**/data-quality.js*',async route=>{requests++;if(requests===1)return route.fulfill({status:503,body:'unavailable'});await gate;return route.continue();});
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'数据质量雷达',exact:true}).click();
  await page.getByRole('button',{name:'重新加载工具',exact:true}).click();
  await page.getByRole('button',{name:'车辆',exact:true}).first().click();release();
  await page.waitForFunction(()=>!!window.DataQualityPage);assert.equal(await page.locator('#page-heading').innerText(),'车辆','late script does not navigate back');
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'数据质量雷达',exact:true}).click();await page.locator('#quality-start').waitFor();
  assert.equal(requests,2,'failed load can retry and successful module is reused');
  await page.getByRole('button',{name:'用车账本',exact:true}).click();await page.locator('#ledger-month').waitFor();
  await page.locator('#ledger-month').fill('2026-09');await page.getByRole('button',{name:'读取账本',exact:true}).click();await page.locator('#ledger-range').waitFor();
  const url=page.url();await page.reload();await page.locator('#ledger-range').waitFor();assert.equal(await page.locator('#ledger-month').inputValue(),'2026-09');assert.equal(page.url(),url,'reload restores query after lazy module mounts');
  let finishLife;const lifeGate=new Promise(resolve=>finishLife=resolve);
  await page.route('**/vehicle-life.js*',async route=>{await lifeGate;return route.continue();});
  await page.getByRole('button',{name:'生活账本',exact:true}).click();
  await page.evaluate(()=>insightsPage.openDate('life','2026-01-15'));
  await page.route('**/api/state',async route=>{const response=await route.fetch();const data=await response.json();await route.fulfill({json:{...data,insights_context:'new-fixture-account'}});});
  await page.evaluate(()=>{state={...state,insights_context:'new-fixture-account'};render();});finishLife();
  await page.locator('#life-start').waitFor();assert.notEqual(await page.locator('#life-start').inputValue(),'2026-01-01','old-account queued navigation discarded');
  assert.equal(await page.locator('#life-form').count(),0);
  let finishCalendar;const calendarGate=new Promise(resolve=>finishCalendar=resolve);
  await page.route('**/usage-calendar.js*',async route=>{await calendarGate;return route.continue();});
  await page.getByRole('button',{name:'用车日历',exact:true}).click();
  await page.evaluate(()=>insightsPage.openDate('calendar','2026-01-15'));
  await page.evaluate(()=>{state={...state,insights_context:'another-fixture-account'};render();});finishCalendar();
  await page.locator('#calendar-month').waitFor();assert.notEqual(await page.locator('#calendar-month').inputValue(),'2026-01','old-account generic input restoration discarded');
  assert.deepEqual(f.errors,[]);assert.deepEqual(f.external,[]);assert.deepEqual(f.posts,[]);
  console.log('LAZY_TOOLS_PASS: overview resources, failure/retry, late completion, single load, URL reload and account isolation');
}finally{await f.close();}})().catch(e=>{console.error(e);process.exitCode=1});
