// Desktop calendar: compact days, honest location fallback, separate record states.
const {fixture,contrast}=require('./ui_insight_helpers.cjs');
const assert=require('node:assert/strict');
(async()=>{const f=await fixture(),{page}=f;try{
 const context=await page.evaluate(()=>state.insights_context),stamp=s=>Date.parse(s+'+08:00');
 const base={category:'same_day',start_trip_id:'a',end_trip_id:'b',start_soc:70,end_soc:69,soc_drop:1,estimated_kwh:.75,status:'comparable',parking_status:'parked',open:false,reason_labels:[],sample_count:4,gap_count:0,p_gear_samples:4,place_label:'公司停车场',place_source:'manual'};
 const events=Array.from({length:5},(_,i)=>({...base,id:'day-'+i,start_time:stamp(`2026-09-29T${String(i+8).padStart(2,'0')}:00:00`),end_time:stamp(`2026-09-29T${String(i+8).padStart(2,'0')}:30:00`),duration_seconds:1800}));
 events.push({...base,id:'long',place_label:'位置未知',status:'uncertain',soc_drop:null,estimated_kwh:null,start_time:stamp('2026-09-29T00:00:00'),end_time:stamp('2026-09-29T07:00:00'),duration_seconds:25200,reason_labels:['停车期间有数据缺口'],observation_quality:{read_count:180,fresh_samples:2,repeat_reads:178,invalid_reads:148,last_vehicle_time:stamp('2026-09-29T07:00:00'),last_read_time:stamp('2026-09-29T07:00:03'),max_gap_seconds:25200,unknown_seconds:25200,gap_count:1},observation_gaps:[{start_time:stamp('2026-09-29T00:00:00'),end_time:stamp('2026-09-29T07:00:00'),duration_seconds:25200}]});
 events.push({...base,id:'candidate',place_label:'位置未知',parking_status:'candidate',status:'uncertain',soc_drop:null,estimated_kwh:null,start_time:stamp('2026-09-29T07:00:00'),end_time:stamp('2026-09-29T07:00:20'),duration_seconds:20});
 events.push({...base,id:'cross',category:'overnight',place_label:'机场停车场',place_confidence:'reference',place_reference_age_seconds:120,start_time:stamp('2026-09-30T23:00:00'),end_time:stamp('2026-10-01T01:00:00'),duration_seconds:7200,soc_drop:2,estimated_kwh:1.5});
 events.push({...base,id:'zero',place_label:'家',start_time:stamp('2026-10-02T08:00:00'),end_time:stamp('2026-10-02T09:00:00'),duration_seconds:3600,soc_drop:0,estimated_kwh:0,charged_soc_gain:5,charging_phases:[{start_time:stamp('2026-10-02T08:15:00'),end_time:stamp('2026-10-02T08:45:00'),duration_seconds:1800}]});
 const data={context,start_date:'2026-09-29',end_date:'2026-10-02',calculation_version:6,events,parking_count:8,uncertain_count:2,orphan_count:0};let requests=0,fail=false;
 await page.route('**/api/insights/parking?*',route=>{requests++;return route.fulfill(fail?{status:500,json:{error:'合成分析失败'}}:{json:data});});
 await page.getByRole('button',{name:'能源与充电',exact:true}).first().click();await page.getByRole('button',{name:'停车观测',exact:true}).click();
 const loadButton=await page.locator('#parking-load').elementHandle();await page.locator('#parking-start').fill(data.start_date);await page.locator('#parking-end').fill(data.end_date);await page.getByRole('heading',{name:'停车观测',exact:true}).click();assert.equal(await loadButton.evaluate(el=>el.isConnected),true,'date editing must retain the analysis button');await page.getByRole('button',{name:'分析停车观测',exact:true}).click();
 await page.locator('[data-parking-date="2026-09-29"]').waitFor();await page.locator('[data-parking-date="2026-09-29"] button').click();
 assert.match(await page.locator('#parking-day-2026-09-29').innerText(),/停车 9小时30分/);
 assert.equal(await page.locator('.parking-calendar-grid [data-parking-entry]').count(),0,'days contain summaries only');
 assert.equal(await page.locator('#parking-day-list [data-parking-entry]').count(),7,'all daily records are available without expansion');
 assert.equal(await page.locator('#parking-day-list [data-parking-entry]').first().getAttribute('data-session'),'long','long confirmed parking precedes brief candidates');
 const long=page.locator('[data-parking-session="long"]');assert.match(await long.locator('.parking-calendar-place').innerText(),/00:00 — 07:00/);assert.match(await long.innerText(),/已确认停车/);assert.match(await long.innerText(),/耗电未知/);
 assert.match(await page.locator('[data-parking-session="candidate"]').innerText(),/停车待确认/);
 assert.doesNotMatch(await page.locator('#parking-day-list').innerText(),/公司停车场|位置未知/);assert.equal(await page.locator('.parking-day-place').count(),0);await long.click();await page.getByRole('dialog').waitFor();assert.match(await page.locator('#parking-detail').innerText(),/数据缺口/);assert.match(await page.locator('#parking-detail').innerText(),/有效车辆观测\s*2 条/);assert.match(await page.locator('#parking-detail').innerText(),/缓存重复读取\s*178 次/);await page.locator('.parking-observation-gaps summary').click();assert.match(await page.locator('.parking-observation-gaps').innerText(),/07:00:00/);await page.getByRole('button',{name:'关闭停车详情',exact:true}).click();
 assert.match(await page.locator('#parking-day-2026-09-30').innerText(),/停车 1小时/);await page.locator('[data-parking-date="2026-09-30"] button').click();assert.match(await page.locator('[data-parking-entry="cross"]').innerText(),/跨日/);assert.doesNotMatch(await page.locator('[data-parking-entry="cross"]').innerText(),/1\.5 kWh/);
 await page.getByRole('button',{name:'下一月',exact:true}).click();assert.match(await page.locator('#parking-day-2026-10-01').innerText(),/停车 1小时/);await page.locator('[data-parking-date="2026-10-01"] button').click();assert.match(await page.locator('[data-parking-session="cross"]').innerText(),/1\.5 kWh/);assert.doesNotMatch(await page.locator('[data-parking-session="cross"]').innerText(),/机场停车场|参考位置/);await page.locator('[data-parking-session="cross"]').click();await page.getByRole('dialog').waitFor();assert.match(await page.getByRole('dialog').innerText(),/机场停车场.*参考位置/);await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
 await page.locator('[data-parking-date="2026-10-02"] button').click();assert.match(await page.locator('[data-parking-session="zero"]').innerText(),/未见 SOC 下降/);await page.locator('[data-parking-session="zero"]').click();assert.match(await page.locator('#parking-detail').innerText(),/停车内充电/);await page.getByRole('button',{name:'关闭停车详情',exact:true}).click();
 fail=true;await page.getByRole('button',{name:'分析停车观测',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.locator('[data-parking-session="zero"]').count(),1);
 for(const theme of ['light','dark']){await page.getByLabel('外观',{exact:true}).selectOption(theme);for(const width of [1440,1280,1024]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await contrast(page);assert.equal(await page.locator('.parking-day-select').evaluateAll(els=>els.some(el=>el.scrollHeight>el.clientHeight)),false,'day summary must fit its button');}}
 assert.deepEqual(f.errors,[]);console.log('DESKTOP_PARKING_CALENDAR_PASS');
}finally{await f.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
