const assert=require('node:assert/strict');
const {fixture}=require('./ui_insight_helpers.cjs');
(async()=>{const f=await fixture(),{page}=f;try{
  const nav=page.locator('#navigation [data-page="car"]');await nav.focus();await nav.press('Enter');
  assert.equal(await page.evaluate(()=>document.activeElement?.id),'page-heading','explicit navigation focuses page title');
  await page.locator('#navigation [data-page="overview"]').focus();await page.evaluate(()=>render());
  assert.equal(await page.evaluate(()=>document.activeElement?.dataset.page),'overview','poll repaint preserves sidebar focus');
  const context=await page.evaluate(()=>state.insights_context);
  const costs={context,as_of:Date.now(),window:{start_date:'2026-10-01',end_date:'2026-10-31'},totals:{actual_cents:17000,charge_cents:10000,charge_parking_cents:2000,life_cents:5000,actual_charge_count:1,life_count:1,unknown_charge_count:0,unlinked_charge_count:0},duplicates:[]};
  await page.route('**/api/insights/costs?*',r=>r.fulfill({json:costs}));
  await page.getByRole('button',{name:'总览',exact:true}).first().click();
  await page.waitForFunction(()=>!document.querySelector('#overview-records')?.textContent.includes('正在读取已保存记录'));
  await page.locator('[data-overview-reload]').click();
  await page.waitForFunction(()=>document.querySelector('#overview-cost-value')?.textContent==='170');
  assert.match(await page.locator('#overview-cost-note').innerText(),/日常支出/);
  await page.getByRole('button',{name:'用车账本',exact:true}).click();await page.getByRole('button',{name:'费用总览',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#books-totals strong')?.textContent==='170.00 元');
  await page.getByRole('button',{name:'充电账本',exact:true}).click();await page.locator('#ledger-range').waitFor();
  assert.equal(await page.locator('#ledger-sources').count(),0,'empty ledger has no empty source panels');
  assert.equal(await page.getByRole('heading',{name:'近六个月费用记录',exact:true}).count(),0);
  await page.getByRole('button',{name:'新增账单',exact:true}).click();await page.locator('#ledger-note').fill('保留草稿');
  await page.evaluate(()=>render());assert.equal(await page.locator('#ledger-note').inputValue(),'保留草稿');
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'数据质量雷达',exact:true}).click();
  await page.locator('#quality-start').waitFor();
  assert.doesNotMatch(await page.locator('#insights-workspace').innerText(),/默认采集间隔 60 秒|降至 300 秒/);
  await page.getByRole('button',{name:'采集与设置',exact:true}).click();
  const health={context,as_of:Date.now(),services:{reports:{status:'disabled',enabled:false,online:false,next_due:null}},summary:{failed_events:1,uncertain_events:0,pending_events:0},events:[{id:'synthetic',kind:'trip_end',created_at:Date.now(),parts:{bark:{state:'sent'},text:{state:'sent'},image:{state:'failed',error_code:'image_prepare_failed'}}}],periodic_reports:[]};
  await page.route('**/api/notifications/health',r=>r.fulfill({json:health}));
  await page.locator('[data-detail="settings-notifications"] > summary').click();
  await page.locator('#notification-health').getByText('图片准备失败',{exact:false}).waitFor();
  assert.match(await page.locator('#notification-health').innerText(),/未启用/);
  health.summary.complete=false;
  health.services.reports={enabled:true,online:true,next_due:{day:'2026-10-09 00:10'}};
  health.periodic_reports=[{period:'day',start_date:'2026-10-07',end_date:'2026-10-07',parts:{text:{state:'sent'},image:{state:'failed',error_code:'preparation_failed'}}}];
  await page.locator('[data-notification-health]').click();
  await page.locator('#notification-health').getByText('部分通知来源暂不可用',{exact:false}).waitFor();
  assert.match(await page.locator('#notification-health').innerText(),/下次计划：日报 2026-10-09 00:10/);
  assert.match(await page.locator('#notification-health').innerText(),/2026-10-07 — 2026-10-07/);
  assert.deepEqual(f.posts,[]);assert.deepEqual(f.errors,[]);assert.deepEqual(f.external,[]);
  for(const theme of ['light','dark']){await page.getByLabel('外观',{exact:true}).selectOption(theme);for(const width of [1440,1280,1024]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}}
  console.log('REVIEW_UI_PASS: focus, shared costs, empty ledger, draft, sampling and read-only notification health');
}finally{await f.close();}})().catch(e=>{console.error(e);process.exitCode=1});
