const assert=require('node:assert/strict');
const {fixture,layouts}=require('./ui_insight_helpers.cjs');
(async()=>{const f=await fixture(),{page}=f;try{
 await page.evaluate(async()=>{
  let book=await fetch('/api/insights/life?start=2026-09-01&end=2026-09-30').then(r=>r.json()),revision=book.expenses.revision;
  const rows=[{date:'2025-02-01',title:'去年保险',category:'保险',amount:'3000',note:'历史保单'},{date:'2026-08-28',title:'八月洗车',category:'洗车',amount:'20',note:'纸质票据'},{date:'2026-09-20',title:'九月停车',category:'停车',amount:'0',note:'免费 ABC'}];
  for(let i=0;i<11;i++)rows.push({date:'2026-09-'+String(i+1).padStart(2,'0'),title:'合成记录'+i,category:'停车',amount:'1',note:''});
  for(const row of rows){const response=await fetch('/api/insights/life',{method:'POST',headers:{'Content-Type':'application/json','X-Request-Key':state.request_key},body:JSON.stringify({collection:'expenses',action:'save',context:book.context,revision,...row})});if(!response.ok)throw Error('fixture save failed');revision=(await response.json()).revision;}
 });
 await page.getByRole('button',{name:'用车账本',exact:true}).click();await page.getByRole('button',{name:'生活账本',exact:true}).click();await page.locator('#life-total').waitFor();await page.getByRole('button',{name:'全部历史',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.life-history-summary')?.textContent.includes('匹配 14 笔'));
 assert.equal(await page.locator('[data-life-expense]').count(),10);assert.equal(await page.locator('[data-life-expense] time').first().innerText(),'2026-09-20');await page.getByRole('button',{name:'下一页生活记录',exact:true}).click();assert.deepEqual(await page.locator('.life-history-month-heading h4').allTextContents(),['2026年09月','2026年08月','2025年02月']);
 const search=page.getByLabel('搜索历史记录',{exact:true});await search.fill('ABC');assert.equal(await page.locator('[data-life-expense]').count(),1);assert.match(await page.locator('.life-history-amount').innerText(),/0\.00 元/);await page.locator('.life-history-details summary').click();assert.match(await page.locator('.life-history-details').innerText(),/免费 ABC/);
 await page.reload();await search.waitFor();assert.equal(await search.inputValue(),'ABC');await page.locator('[data-life-expense]').waitFor();await page.getByRole('button',{name:'删除支出',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.life-history-summary')?.textContent.includes('匹配 0 笔'));await page.getByLabel('支出记录状态',{exact:true}).selectOption('deleted');await page.getByRole('button',{name:'恢复支出',exact:true}).waitFor();assert.match(await page.locator('.life-history-summary').innerText(),/已删除合计（不计费用）/);await page.getByRole('button',{name:'恢复支出',exact:true}).click();await page.getByLabel('支出记录状态',{exact:true}).selectOption('active');await page.locator('[data-life-expense]').waitFor();
 await search.fill('');await page.getByLabel('分类筛选',{exact:true}).selectOption('');await page.getByRole('button',{name:'全部历史',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.life-history-summary')?.textContent.includes('匹配 14 笔'));await page.getByRole('button',{name:'下一页生活记录',exact:true}).click();await layouts(page,'life-history');
 assert.deepEqual(f.errors,[]);assert.deepEqual(f.external,[]);console.log('LIFE_HISTORY_UI_PASS: all history, month grouping, pagination, search, zero cost, refresh, trash and restore, desktop themes and zoom');
}finally{await f.close()}})().catch(e=>{console.error(e);process.exitCode=1});
