const assert=require('node:assert/strict');
const {fixture,layouts}=require('./ui_insight_helpers.cjs');
(async()=>{
  const f=await fixture(),{page}=f;
  try{
    await page.getByRole('button',{name:'生活账本',exact:true}).click();
    await page.getByLabel('生活账本月份',{exact:true}).fill('2026-09');
    await page.getByRole('button',{name:'读取生活账本',exact:true}).click();
    await page.getByLabel('支出日期',{exact:true}).fill('2026-09-20');
    await page.getByLabel('支出分类',{exact:true}).fill('合成分类');
    await page.getByLabel('支出名称',{exact:true}).fill('洗车 <img src=x onerror=alert(1)>');
    await page.getByLabel('实际支出金额（元）',{exact:true}).fill('30.10');
    await page.getByLabel('支出备注',{exact:true}).fill('仅测试本机持久化');
    await page.evaluate(()=>render());
    assert.equal(await page.getByLabel('支出备注',{exact:true}).inputValue(),'仅测试本机持久化');
    await page.getByRole('button',{name:'保存支出',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#life-total')?.textContent.includes('30.10'));
    assert.equal(await page.locator('[data-life-expense] img').count(),0);
    await page.getByRole('button',{name:'编辑支出',exact:true}).click();
    await page.getByLabel('实际支出金额（元）',{exact:true}).fill('35.20');
    await page.getByRole('button',{name:'保存支出',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#life-total')?.textContent.includes('35.20'));
    await page.getByRole('button',{name:'撤销支出操作',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#life-total')?.textContent.includes('30.10'));
    await page.getByRole('button',{name:'删除支出',exact:true}).click();
    await page.getByLabel('支出记录状态',{exact:true}).selectOption('deleted');
    await page.getByRole('button',{name:'恢复支出',exact:true}).click();
    await page.getByLabel('支出记录状态',{exact:true}).selectOption('active');
    await page.locator('[data-life-expense]').waitFor();
    assert.match(await page.locator('#life-total').locator('..').innerText(),/合成分类 · 1 笔\s+30.10 元/);
    await layouts(page,'vehicle-life-expenses');
    await page.getByRole('button',{name:'保养与到期待办',exact:true}).click();
    await page.getByLabel('待办名称',{exact:true}).fill('合成保险续期');
    await page.getByLabel('到期日期',{exact:true}).fill('2026-09-20');
    await page.getByLabel('到期里程（km）',{exact:true}).fill('20000');
    await page.getByRole('button',{name:'保存待办',exact:true}).click();
    await page.locator('[data-life-reminder]').waitFor();
    assert.match(await page.locator('[data-life-reminder]').innerText(),/已到期/);
    await page.getByRole('button',{name:'标记完成',exact:true}).click();
    await page.getByLabel('待办筛选',{exact:true}).selectOption('completed');
    await page.getByText(/已完成 ·/).waitFor();
    await page.getByRole('button',{name:'撤销待办操作',exact:true}).click();
    await page.getByLabel('待办筛选',{exact:true}).selectOption('all');
    await page.getByRole('button',{name:'编辑待办',exact:true}).click();
    await page.getByLabel('到期日期',{exact:true}).fill('');
    await page.getByRole('button',{name:'保存待办',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('[data-life-reminder]')?.textContent.includes('里程待确认'));
    await layouts(page,'vehicle-life-reminders');
    await page.reload();await page.getByRole('button',{name:'用车研究',exact:true}).click();
    await page.getByRole('button',{name:'生活账本',exact:true}).click();
    await page.getByRole('button',{name:'保养与到期待办',exact:true}).click();
    await page.locator('[data-life-reminder]').waitFor();
    assert.match(await page.locator('[data-life-reminder]').innerText(),/20,000/);
    await page.getByRole('button',{name:'编辑待办',exact:true}).click();
    await page.getByLabel('待办备注',{exact:true}).fill('保留本地草稿');
    await page.evaluate(async()=>{
      const book=await fetch('/api/insights/life?date=2026-09-20').then(r=>r.json());
      const row=book.reminders.records[0];
      await fetch('/api/insights/life',{method:'POST',headers:{'Content-Type':'application/json','X-Request-Key':state.request_key},body:JSON.stringify({collection:'reminders',action:'save',context:book.context,revision:book.reminders.revision,id:row.id,title:'另一页面已修改',due_date:'',due_km:row.due_km,note:'另一个写入者'})});
    });
    const refresh=page.waitForResponse(r=>r.url().includes('/api/insights/life?')&&r.request().method()==='GET');
    await page.evaluate(async()=>{const real=Date.now;Date.now=()=>real()+31000;try{await pollState(true);}finally{Date.now=real;}});
    await refresh;
    await page.locator('[data-life-reminder]').filter({hasText:'另一页面已修改'}).waitFor();
    assert.equal(await page.getByLabel('待办备注',{exact:true}).inputValue(),'保留本地草稿');
    await page.getByRole('button',{name:'保存待办',exact:true}).click();
    await page.getByRole('alert').filter({hasText:'记录已有更新'}).waitFor();
    await page.getByRole('button',{name:'已核对列表，继续编辑',exact:true}).click();
    await page.getByRole('button',{name:'保存待办',exact:true}).click();
    await page.locator('[data-life-reminder]').filter({hasText:'保留本地草稿'}).waitFor();
    assert.ok(f.posts.every(url=>url===f.origin+'/api/insights/life'));
    assert.deepEqual(f.external,[]);assert.deepEqual(f.errors,[]);
    console.log('UI_VEHICLE_LIFE_PASS: expense categories/cents/edit/undo/delete/restore, dated and mileage tasks/completion/undo/unknown mileage, persistence, XSS, poll preservation, themes/mobile/zoom/contrast; local writes only');
  }finally{await f.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
